default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: root
  # password: student4808
  database: est_dev

production:
  <<: *default
  username: root
  database: est_production