default: &default
  adapter: postgresql
  encoding: unicode
  password: student4808
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  username: obroshnij
  database: est_dev

production:
  <<: *default
  username: obroshnij
  database: est_production

test:
  <<: *default
  username: obroshnij
  database: est_test