default: &default
  adapter: postgresql
  encoding: unicode
  password: student4808
  pool: 5

development:
  <<: *default
  username: obroshnij
  database: est_dev

production:
  <<: *default
  username: obroshnij
  database: est_production

test:
  <<: *default
  username: obroshnij
  database: est_test